In [7]:
import numpy as np
a = np.array([[1, 2, 4], [5, 8, 7]])
print("Array created using passed list:\n", a)


Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [9]:
# Creating a 3X4 array with all zeros
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)



An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#Create a constant value array of complex type
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [11]:
#Create an array with random values
d = np.random.random((2, 2))
print ("\nA random array:\n", d)



A random array:
 [[0.06616165 0.60569956]
 [0.67265611 0.13447025]]


In [12]:
# Create a sequence of integers from 0 to 30 with steps of 5
e = np.arange(0, 30, 5)
print ("\n A sequential array with steps of 5:\n", e)


 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [14]:
#Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4], [5, 2, 4, 2],[1, 2, 0, 1]])
newarr = arr.reshape(4, 3)
print ("\nOriginal array:\n", arr)
print ("Reshaped array[4,3]:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [15]:
#Flatten array
flarr= arr.flatten()
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr) 


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [1]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,2,4,2],
                [1,2,0,1]])

print("\nNo. of dimensions: ", arr.ndim)
print("\nShape of array: ", arr.shape)
print("\nSize of array: ", arr.size)
print("\nArray stores elements of type:", arr.dtype)

# converting from integer to float
new_arr = arr.astype('float')

print("\nConverted array elements:\n", new_arr)
print("Converted array type:", new_arr.dtype)


No. of dimensions:  2

Shape of array:  (3, 4)

Size of array:  12

Array stores elements of type: int64

Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float64


In [2]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


In [3]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2,0:2])

[7 8]


In [4]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2:,2:])

[[ 9]
 [12]
 [15]]


In [5]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:,3:])

[]


In [11]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[:,1])
Explanation:
 p is a 5 × 3 array.
 p[:, 1] means:
o : → select all rows
o 1 → select the second column (index starts from 0)

So the elements taken are:

[ 2  5  8 11 14]


'Explanation:\n\uf0b7 p is a 5 × 3 array.\n\uf0b7 p[:, 1] means:\no : → select all rows\no 1 → select the second column (index starts from 0)\n\nSo the elements taken are:'

In [7]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('f')
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [10]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


'\njufjhjdk\n'